export const SET_USERS_REQUESTED = "SET_USERS_REQUESTED";
export const SET_USERS_FILTERED_REQUESTED = "SET_USERS_FILTERED_REQUESTED";
export const SET_USERS_SUCCESS = "SET_USERS_SUCCESS";
export const SET_USERS_FILTERED_SUCCESS = "SET_USERS_FILTERED_SUCCESS";
export const SET_USERS_FAILED = "SET_USERS_FAILED";
export const SET_USERS_PAGINATION_DATA = "SET_USERS_PAGINATION_DATA";
export const SET_USERS_PAGINATION_CURRENT_PAGE = "SET_USERS_PAGINATION_CURRENT_PAGE";